### PR TITLE
Sorin.py

### PR DESCRIPTION
**Pull request by Sorin-tech**
another update.

### CODE REVIEW

**Comment by johnsani** [comment]
check your print statement again.

**Comment by AyoPips** [comment]
He had deleted it a merge is possible

**Review by ghost — COMMENTED** [review]
CA the function at the end of the file

**Review by ghost — APPROVED** [review]

**Review by maroafenogho — COMMENTED** [review]
Try changing the variable name ID ti id

**Review by ghost — COMMENTED** [review]
Try changing the ID to lowercase

**Comment by maroafenogho** [comment]
You're good.

**Pull request merged**
