### PR TITLE
add my script

### PR DESCRIPTION
**Pull request by Aigberua121**
This is my first script for this task

### CODE REVIEW

**Review by thebolarin — APPROVED** [review]

**Comment by Aigberua121** [comment]
Thank you

**Comment by piouson** [comment]
Hey just leaving you a feedback, your work is merged but didn't appear in the test page when I checked. Please review your work and check with the team leaders, just in case..

**Comment by Aigberua121** [comment]
My work has been Marge's but dint show on the test page what's going on?
Please help me to review it

**Comment by piouson** [comment]
@Aigberua121 Not sure idea but did you message the team leaders to find out what went wrong..?

**Pull request merged**
