### PR TITLE
my JS script is ready

### PR DESCRIPTION
**Pull request by juniorndem**

### CODE REVIEW

**Review by alexismajya — COMMENTED** [review]
Hello Dieudonne! good job. however, the output message doesn't rely on regex. move text4 and email before text3

**Review by Francisop — CHANGES_REQUESTED** [review]
please restructure your code appropriately and console.log your result not alert

**Comment by Rubylena** [comment]
am waiting. ask for help here https://hngi7.slack.com/archives/C01482Z0095/p1591369072416800

**Comment by malikmukhtar** [comment]
@juniorndem use console.log not alert

**Pull request closed without merging**
