### PR TITLE
Update ThomasTsuma.py

### PR DESCRIPTION
**Pull request by TomiTsuma**

### CODE REVIEW

**Comment by FaithMo** [comment]
Please resolve these merge conflicts before your file can be merged.

**Review by ghost — APPROVED** [review]

**Review by Francisop — CHANGES_REQUESTED** [review]
please remove the conflict by deleting the code highlighted in red

**Review by ghost — COMMENTED** [review]
Resolve  the  conflict

**Comment by Rubylena** [comment]
closing this. ask help here https://hngi7.slack.com/archives/C01482Z0095/p1591369072416800

**Review by ghost — CHANGES_REQUESTED** [review]
Resolve Conflicts

**Pull request closed without merging**
