### PR TITLE
Add mutugi.py

### PR DESCRIPTION
**Pull request by Mutugiii**

### CODE REVIEW

**Comment by Mutugiii** [comment]
@thebolarin @dave-ok @qobitech  Could any of you kindly review this

**Comment by Mutugiii** [comment]
@dro-1 Could you kindly review this PR! I would gladly appreciate :)

**Comment by dro-1** [comment]
the code is not running. Wrong indentation

**Comment by Mutugiii** [comment]
@dro-1 I have added some changes now, indentation seemed ok though

**Review by ghost — APPROVED** [review]

**Comment by Rubylena** [comment]
not merging, work on your code and send another PR. ask help here https://hngi7.slack.com/archives/C01482Z0095/p1591369072416800

**Pull request closed without merging**
