### PR TITLE
My new branch

### PR DESCRIPTION
**Pull request by aremcx**
My re push HNGi7 task 2.

### CODE REVIEW

**Review by aremcx — COMMENTED** [review]
have changed the file extension from ipynb to py.  And re pushed.

**Review by Francisop — CHANGES_REQUESTED** [review]
please cross check your code

**Comment by Rubylena** [comment]
python is supposed to be a language variable, where you declare the variable as python. i will accept this merge but if its not accepted....

**Comment by aremcx** [comment]
Ok, I supposed to declare my language?

**Pull request merged**
