### PR TITLE
Merge Request

### PR DESCRIPTION
**Pull request by TomiTsuma**

### CODE REVIEW

**Comment by dro-1** [comment]
Follow the directives of how the output should be

**Comment by TomiTsuma** [comment]
Hi Could you please explain what you mean? Because when I use the format
with the email it fails and I have noticed the same of a lot of other ones.
Kindly explain what I should do because if you don't merge this I can't see
what happens if I use  the format which I am seeing has more success

**Comment by dro-1** [comment]
Follow what we posted on the slack channel and you won't have issues

**Comment by Peacepac** [comment]
please her use this format
and you should not touch what is inside the console.log()
All the place I put XYZ the person should change it to something else


 function XYZ(){
 
       const id = 'HNG-XYZ';
    const email = 'XYXY@gmail.com';
  const language = 'javascript';
 const fullname = 'XYZ XYZ';
 
 
 
   console.log('Hello World, this is '+ fullname+ ' with HNGi7 ID '+ id + ' and email ' + email +' using '+ language + ' for stage 2 task');
 
 
 
 }
 
 XYZ();

**Comment by TomiTsuma** [comment]
Kindly check it out now. I have decided to use python

**Comment by Rubylena** [comment]
if your using the py file then delete the js file

**Pull request merged**
