### PR TITLE
Biddyman.js

### PR DESCRIPTION
**Pull request by Biddyman**
Please help me merge.Sorry i came late

### CODE REVIEW

**Review by maroafenogho — CHANGES_REQUESTED** [review]
"e-mail" should be "email"

**Review by Biddyman — COMMENTED** [review]
Error corrected, thanks

**Comment by maroafenogho** [comment]
The error is still there. The value of your email variable should be "and email" not "and e-mail"

**Comment by Biddyman** [comment]
I did correct it, I am surprised it's still there. Sent from my Huawei phone-------- Original Message --------Subject: Re: [hng-teamfury/team-fury-1] Biddyman.js (#822)From: Oghenemaro Afenogho To: hng-teamfury/team-fury-1 CC: Biddyman ,Author 
The error is still there. The value of your email variable should be "and email" not "and e-mail"

**Comment by maroafenogho** [comment]
You still haven't corrected it. Please do so quickly

**Comment by maroafenogho** [comment]
Your text 3 should return "and email". Please implement the correction quickly.

**Pull request merged**
