### PR TITLE
Create mrkellard.js

### PR DESCRIPTION
**Pull request by Mrkellard**
Please I expect your feedback

### CODE REVIEW

**Comment by Mrkellard** [comment]
Please merge this updated request

**Review by FaithMo — CHANGES_REQUESTED** [review]
remove the mrbellad file you created on the root folder.

**Comment by Mrkellard** [comment]
I have deleted the file in the root folder. kindly check if its okay and merge.
regards.

**Comment by Arch997** [comment]
You need to add the email to your string. It will not output on the group html cos of the regex. But it's needed for the json. E.g. "Hello World, this is {yourName} with HNGi7 ID {id} and email {email} using {language} for stage 2 task

**Pull request merged**
