### PR TITLE
Akuragba.js

### PR DESCRIPTION
**Pull request by 69codes**
I used Java Scripts for this work

### CODE REVIEW

**Comment by piouson** [comment]
Hey just leaving you a feedback, your work is merged but doesn't appear in the test page. Please review your work and check with the team leaders, just in case..

**Comment by 69codes** [comment]
It's there I saw it.. it failed

**Comment by piouson** [comment]
ah yea something to do with python script error, I'm sure will be fixed soon..

**Comment by 69codes** [comment]
Please, help me check akuragba1.js .. it didn't merge .... I made an error
in the one I posted before...

**Comment by 69codes** [comment]
Its saying review required and merging is blocked

**Comment by piouson** [comment]
But this has been merged. If you wanna make changes its best to submit a new PR and then wait for another merge

**Pull request merged**
