### PR TITLE
Ogu Johnkennedy

### PR DESCRIPTION
**Pull request by mathjken**
My HNG Task one completed using Javascript

### CODE REVIEW

**Review by thebolarin — CHANGES_REQUESTED** [review]
Use your username as the file name and not your id

**Comment by mathjken** [comment]
I have done that since yesterday

**Review by qobitech — CHANGES_REQUESTED** [review]
what he meant is rename your script with your slack username

**Comment by mathjken** [comment]
Done, please check and confirm. Thanks

**Review by dave-ok — APPROVED** [review]

**Comment by mathjken** [comment]
Thanks alot

**Pull request merged**
