### PR TITLE
Abu4kind_my hng7i task for team fury-1

### PR DESCRIPTION
**Pull request by abu4kind**
This Abubakar Adamu interning with HNG7i.

ID _ hng-00826-abu4kind

### CODE REVIEW

**Review by thebolarin — CHANGES_REQUESTED** [review]
Use only your username alone as file name i.e johndoe.js

**Comment by abu4kind** [comment]
Please which file are you talking about, how will I correct this. Can you guide me.
Thanks

**Comment by abu4kind** [comment]
Will I have to the fury file and change this

**Comment by abu4kind** [comment]
That's mean I will need to go and commit from beginning?

**Review by dave-ok — APPROVED** [review]

**Comment by abu4kind** [comment]
So what does this mean, does it mean am fine or good.
Has the task successfully completed

**Pull request merged**
