### PR TITLE
corrected 

### PR DESCRIPTION
**Pull request by Abuh05**

### CODE REVIEW

**Review by simply-alliv — CHANGES_REQUESTED** [review]
1. Please delete one of the Abuh_Solo/abuh_solo files. only one is required.

2. Please remove the extra space in the ID variable' s value ("HNG-05884 "). There's already a space after the ID in the interpolated string.

**Comment by piouson** [comment]
remove all but one file, use

```
git rm scripts/filename.ext scripts/filename2.ext
git commit . -m "Remove bad files"
git push origin <your-git-branch>
```

**Comment by Abuh05** [comment]
I've delete one already

**Comment by Abuh05** [comment]
all necessary correction made... 
https://github.com/hng-teamfury/team-fury-1/pull/660

**Pull request closed without merging**
