### PR TITLE
Sorin

### PR DESCRIPTION
**Pull request by Sorin-tech**

### CODE REVIEW

**Review by dave-ok — CHANGES_REQUESTED** [review]
Your script name should be "yourslackusername.py" and should be in the scripts folder

**Review by FaithMo — APPROVED** [review]

**Review by FaithMo — CHANGES_REQUESTED** [review]
code is fine, change the name of the file.

**Review by Sorin-tech — COMMENTED** [review]
file name has been changed.

**Review by Sorin-tech — COMMENTED** [review]
please review the change.

**Comment by dave-ok** [comment]
Please change your filename from `sorin script.py` to `sorin.py` inside the `/scripts` folder

**Review by FaithMo — APPROVED** [review]

**Pull request merged**
