### PR TITLE
Added my Python script to the scripts folder

### PR DESCRIPTION
**Pull request by Ifihan**

### CODE REVIEW

**Review by ruffcoins — CHANGES_REQUESTED** [review]
This is what your output should look like.
"Hello World, this is {name} with HNGi7 ID {id} using {language} for stage 2 task"

**Comment by Ifihan** [comment]
> This is what your output should look like.
> "Hello World, this is {name} with HNGi7 ID {id} using {language} for stage 2 task"

Thank you, I'll fix it

**Comment by Ifihan** [comment]
I've fixed my script already

**Review by ruffcoins — APPROVED** [review]
It looks perfect

**Comment by Ifihan** [comment]
Thank you! Can it be merged now?

**Pull request merged**
