### PR TITLE
OIyadi

### PR DESCRIPTION
**Pull request by CornerstoneII**
Contribution File has been added.

### CODE REVIEW

**Comment by dro-1** [comment]
only your script file is needed

**Comment by CornerstoneII** [comment]
> only your script file is needed

Piouson Is aware of this.

**Comment by Rubylena** [comment]
look for a way to add the contributing file without conflicts. send a new PR. and make sure you do a git pull before you send it

**Comment by Rubylena** [comment]
use a new branch for it. am closing this

**Pull request closed without merging**
