### PR TITLE
Update script - I have edited the commas and column

### PR DESCRIPTION
**Pull request by fayeloja**

### CODE REVIEW

**Comment by dro-1** [comment]
Wrong script output

**Comment by alxzndr2019** [comment]
wrong output correct yourself

**Review by maroafenogho — CHANGES_REQUESTED** [review]
Please check for extra spaces. Remove the extra space after PHP

**Review by maroafenogho — CHANGES_REQUESTED** [review]
Remove all other files. 
We only need your script

**Comment by fayeloja** [comment]
*Done*
*Best regards,*
*Fatai Ayeloja*

**Comment by dro-1** [comment]
Change only your script. Remove all other files

**Pull request closed without merging**
