### PR TITLE
Create Ismail.py

### PR DESCRIPTION
**Pull request by Muni-Ismail**
My Hello World script

### CODE REVIEW

**Comment by Arch997** [comment]
Your script is incorrect. Run your print statement inside your function. And make sure your call your function.

**Review by ghost — CHANGES_REQUESTED** [review]
You have to call the function you created at the end of your file

**Review by ghost — CHANGES_REQUESTED** [review]
Those function variables can't be accessed cos they are local..... Under the print statement in the function and call the function

**Comment by Muni-Ismail** [comment]
My Hello World Script updated.

**Review by ghost — COMMENTED** [review]
Put the print statement inside the function  and Call the function  at the end

**Comment by Muni-Ismail** [comment]
My Hello World script.

**Comment by Rubylena** [comment]
what is going on here. is the code good to go. reviewers?

**Review by ghost — APPROVED** [review]

**Review by Francisop — APPROVED** [review]

**Pull request merged**
