### PR TITLE
edited copy

### PR DESCRIPTION
**Pull request by FunsoAdetola**

### CODE REVIEW

**Comment by mocktarissa** [comment]
The format you used will return failed use instead : 
"Hello World, this is [full name] with HNGi7 ID [ID] and email [email] using [language] for stage 2 task".
I do not have write access. It's just to help you out.

**Review by FaithMo — CHANGES_REQUESTED** [review]
The funsoadelota.py that's in the root folder is not supposed to be there. Please delete it.

**Comment by FunsoAdetola** [comment]
Thanks a lot

**Comment by FunsoAdetola** [comment]
this is my edited copy

**Pull request merged**
