### PR TITLE
Pull request for branch Paul HNGi7

### PR DESCRIPTION
**Pull request by ajadi473**
Added the python file to output the required strings

### CODE REVIEW

**Comment by FaithMo** [comment]
your file name needs to be the username you use on slack.

**Comment by ajadi473** [comment]
> your file name needs to be the username you use on slack.

Thanks i have changed the filename

**Comment by ajadi473** [comment]
Thanks, it has been corrected

**Comment by ajadi473** [comment]
@dave-ok can you please help

**Comment by dave-ok** [comment]
@ajadi473 why did you delete godstime.js. Please restore it

**Comment by ajadi473** [comment]
I’m sorry I have it restored

**Comment by ajadi473** [comment]
thanks, i lorrr yo!!

**Pull request merged**
