### PR TITLE
Kodak Ewa file

### PR DESCRIPTION
**Pull request by Ewamiee**
I just sent it

### CODE REVIEW

**Comment by dro-1** [comment]
Remove the script in the root folder

**Review by ghost — COMMENTED** [review]
script looks great...... just remove from root folder

**Review by ghost — COMMENTED** [review]
looks ok......try using Fstrings to output ..and remove from root folder

**Comment by hng-teamfury** [comment]
@Fortunate245 @dro-1 many thanks for looking into this!!

We shouldn't close a PR in haste, we can always ask others for suggestions if we have to in order to provide a better review.

Replace spaces with dash `-` in filename and remove stale files.

- [ ] Change `scripts/kodak Ewa.py` to `scripts/kodak-ewa.py`
- [ ] Delete `kodak Ewa.py` with `git rm "kodak Ewa.py"`
- [ ] Add changes made with `git add scripts/kodak-ewa.py`
- [ ] Push changes to origin with `git push origin <branch-name>`

> image

Then we can review and merge! :)

**Review by alxzndr2019 — APPROVED** [review]

**Pull request merged**
