### PR TITLE
this should work now

### PR DESCRIPTION
**Pull request by Brown-coder**
I have made changes please review and merge

### CODE REVIEW

**Review by dhatGuy — CHANGES_REQUESTED** [review]
Three errors now
1. There should be space after the ID
2. Remove "address". It is just "email" without "address"
3. Remove the comma after your email

**Review by alexismajya — CHANGES_REQUESTED** [review]
remove address and comma before using

**Review by alexismajya — COMMENTED** [review]
also add space between ID and $

**Comment by dro-1** [comment]
Use normal quotes in your console.log

**Comment by Rubylena** [comment]
closing. send another when your `done```

**Pull request closed without merging**
