### PR TITLE
Rewrote README.md for better clarifications on git

### PR DESCRIPTION
**Pull request by Adiomojeed**

### CODE REVIEW

**Comment by piouson** [comment]
@Adiomojeed wow you're adding to this, really good effort!!
Can you edit the PR title to fit work for UI design, this is more than just doc edit now..

**Comment by doncity-tech** [comment]
Ok this is LogicDev

**Comment by piouson** [comment]
See [comment-638505912 in #1](https://github.com/jgodstime/team-fury-1/issues/1#issuecomment-638505912) for current live site demo.
But everyone can work together here to make it better 👍

**Comment by doncity-tech** [comment]
No problem, how far have you guys gone

**Comment by piouson** [comment]
I just found #29 by @kay-ai 
we need to somehow compare and merge his backend code to this..

**Comment by Adiomojeed** [comment]
@piouson I don't know how to change the PR title

**Comment by doncity-tech** [comment]
@Adiomojeed  you can close the PR and do it again

**Comment by doncity-tech** [comment]
@piouson how can I assist on the frontend: https://team-fury.netlify.app/

**Comment by Adiomojeed** [comment]
Ok

**Comment by Extremophile-ai** [comment]
We're dong well

**Comment by piouson** [comment]
@doncity-tech do you use codepen..?

Might be good to move what we have so far to codepen where everyone can see and change the code on the fly..

But we have to compare to what we already have to decide if any need to continue yours or just add to existing code..

Have a look at the [**Live Site**](http://54.236.54.185/team-fury-1/) and maybe look into how to:

- Merge your work to that
- Make it a responsive mobile first design

**Comment by doncity-tech** [comment]
Yea I use codepen

**Comment by doncity-tech** [comment]
Have a look at mine: https://team-fury.netlify.app/
and my PR: https://github.com/jgodstime/team-fury-1/pull/68

**Pull request closed without merging**
