### PR TITLE
Smizzy.py

### PR DESCRIPTION
**Pull request by Smizzy01**
HNG-04859

### CODE REVIEW

**Review by thebolarin — CHANGES_REQUESTED** [review]
Hello,make your file name to your slack username.

**Comment by Smizzy01** [comment]
@thebolarin pls Bolarin check if I have made the appropriate changes

**Comment by Smizzy01** [comment]
@thebolarin good morning sir, please check my work

**Review by Smizzy01 — COMMENTED** [review]
Made some significant changes

**Review by dave-ok — APPROVED** [review]

**Pull request merged**
