### PR TITLE
Create solomon.js

### PR DESCRIPTION
**Pull request by chimeziesolomon**
solomon's file

### CODE REVIEW

**Comment by AbisoyeAlli** [comment]
Console.log your function call

**Comment by dro-1** [comment]
Your string is a multiline string.Change it to single line and your output doesn't follow the pattern

**Comment by chimeziesolomon** [comment]
thanks guys it was the regex that could not match my email the teamlead's attention has been called to it

**Comment by maroafenogho** [comment]
Please do as you have been advised and edit your code. It still isn't running.

**Comment by Rubylena** [comment]
i will accept this but if it doesnt display then not my fault

**Comment by Rubylena** [comment]
opps i can't merge, put your script into the script folder

**Pull request closed without merging**
