### PR TITLE
Ann's Commit

### PR DESCRIPTION
**Pull request by Ann-design-max**

### CODE REVIEW

**Review by thebolarin — APPROVED** [review]

**Comment by Ann-design-max** [comment]
Thank you and keep up the good work

**Comment by piouson** [comment]
Hey just leaving you a feedback, test page shows yours is a fail. Please review your work and check with the team leaders..

**Comment by Ann-design-max** [comment]
Thank you very much for your feedback and time. I have decided to give
up...this internship is not making any sense to me at all... Good luck 💪

**Comment by piouson** [comment]
@Ann-design-max do not give up, I think we messed up with the leadership nomination. We will nominate again after this submission and I promise you that everyone who joined to learn will do just that, learn!
So stick around to support the present leaders, they probably never handled a team this size and also facing a whole new challenge..
After submission we'll do it right, everyone together..

**Comment by dave-ok** [comment]
@Ann-design-max It's unfortunate your script failed but it is not a fault on the side of the leadership rather an error on your part. Your HNG ID is "HNG-00018" and not "HNG-0018" which you used. Its best to review your code and confirm if your code has an issue in cases like this and correct yourself. That's the best way to learn. 

@piouson Please also confirm before placing blames in the wrong direction

**Comment by Ann-design-max** [comment]
Firstly, My JavaScript code worked on my desktop and I was able to see my
name and other details from the console regardless of my ID being was wrong
or not@David .

Secondly, I don't know about you but I'm am beginner hence the reason for
joining this internship. However, the way things are done, don't provide a
good learning environment for me in what is supposed to be an internship.
The coursea classes I'm taking are much better. I just needed someone that
I could ask questions when I run into any difficulty.

I had high hopes that this internship will be it, but sadly it's a jungle
for the survival of the fittest.

Anyway I wish you all the best of luck. Thanks and God Bless.

Regards,
Ann.

**Pull request merged**
